In [1]:
import pandas as pd
import numpy as np
import re
import nfl_data_py as nfl
import redis
import pickle

r = redis.Redis(host='localhost', port=6379)

number_of_teams = 10
is_flex = True
ppr = 1
rush_yards = 0.1
receiving_yards = 0.1
rush_td = 6
receiving_td = 6
pass_yards = 0.04
pass_td = 4
fmb = -2
interception = -2

In [2]:
## load the rosters
def load_rosters(year):
    roster_columns = ['gsis_it_id','season','team','player_name','position']
    retrieved_rosters = r.get(f"rosters_{year}:v1")

    if retrieved_rosters:
        print(f'data loaded from redis for {year}')
        return pickle.loads(retrieved_rosters)
    else:
        print(f'loading data from github for {year}')
        retrieved_rosters = nfl.import_rosters([year], roster_columns)
        r.set(f"rosters_{year}:v1", pickle.dumps(retrieved_rosters))
        return retrieved_rosters

rosters = {}
for year in range(2009,2024):
    rosters[year] = load_rosters(year)

all_rosters = pd.concat(rosters.values(), ignore_index=True)
all_rosters.rename(columns={'gsis_it_id': 'gsis_id', 'player_name': 'full_name'}, inplace=True)

print("**** all rosters top 25 ****")
print(all_rosters.head(25))

data loaded from redis for 2009
data loaded from redis for 2010
data loaded from redis for 2011
data loaded from redis for 2012
data loaded from redis for 2013
data loaded from redis for 2014
data loaded from redis for 2015
data loaded from redis for 2016
data loaded from redis for 2017
data loaded from redis for 2018
data loaded from redis for 2019
data loaded from redis for 2020
data loaded from redis for 2021
data loaded from redis for 2022
data loaded from redis for 2023
**** all rosters top 25 ****
   gsis_id  season team                    full_name position
0      NaN    2009  ARZ                  Ben Claxton        C
1      NaN    2009  ARZ                Lyle Sendlein        C
2      NaN    2009  ARZ                Michael Adams       CB
3      NaN    2009  ARZ                  Ralph Brown       CB
4      NaN    2009  ARZ              Bryant McFadden       CB
5      NaN    2009  ARZ  Dominique Rodgers-Cromartie       CB
6      NaN    2009  ARZ                Gregory Toler       CB
7      NaN    2009  ARZ              Calais Campbell       DE
8      NaN    2009  ARZ                Kenny Iwebema       DE
9      NaN    2009  ARZ                  Alan Branch       DT
10     NaN    2009  ARZ                 Jeremy Clark       DT
11     NaN    2009  ARZ              Darnell Dockett       DT
12     NaN    2009  ARZ           Nehemiah Broughton       FB
13     NaN    2009  ARZ                  Dan Kreider       FB
14     NaN    2009  ARZ               Rashad Johnson       FS
15     NaN    2009  ARZ                 Antrel Rolle       FS
16     NaN    2009  ARZ               Jeremy Bridges        G
17     NaN    2009  ARZ                Brandon Keith        G
18     NaN    2009  ARZ                  Deuce Lutui        G
19     NaN    2009  ARZ                 Reggie Wells        G
20     NaN    2009  ARZ                 Monty Beisel      ILB
21     NaN    2009  ARZ                Karlos Dansby      ILB
22     NaN    2009  ARZ                 Gerald Hayes      ILB
23     NaN    2009  ARZ                Reggie Walker      ILB
24     NaN    2009  ARZ                 Neil Rackers        K

In [3]:
pbp_columns = [
      "pass_attempt", "passer_player_id", "rusher_player_id",
      "receiver_player_id", "play_type", "game_id", "drive",
      "passer_player_name", "complete_pass", "yards_gained",
      "air_yards", "qb_hit", "interception", "touchdown",
      "yards_after_catch", "epa", "wpa", "air_epa", "air_wpa",
      "yac_epa", "yac_wpa", "rush_attempt", "rusher_player_name",
      "fumble", "receiver_player_name", "posteam", "defteam", "Season"]

def store_dataframe_in_redis(name, dataframe):
    r.delete(name)
    serialized_data = pickle.dumps(dataframe)
    r.set(name, serialized_data)

def fetch_dataframe_from_redis(name):
    serialized_data = r.get(name)

    if serialized_data:
      return pickle.loads(serialized_data)
    else:
      return None

def load_pbp(year):
    year_pbp = fetch_dataframe_from_redis(f"pbp_{year}:v1")

    if year_pbp is not None and year_pbp.empty == False:
        print(f'data loaded from redis for {year}')
        return year_pbp
    else:
      print(f'loading data from github for {year}')
      year_pbp = nfl.import_pbp_data([year])
      store_dataframe_in_redis(f'pbp_{year}:v1', year_pbp)
      return year_pbp

def find_player_name(player_names):
    if len(player_names) == 0:
        return "None"
    else:
        return player_names.value_counts().idxmax()
    
def calc_passing_splits(splits, pbp_df):
    pbp_df = pbp_df.copy()

    # Filter data for pass attempts and add the GameDrive column
    pbp_df = pbp_df[(pbp_df['pass_attempt'] == 1) & (pbp_df['play_type'] != 'No Play')]
    #pbp_df['GameDrive'] = pbp_df['game_id'].astype(str) + "-" + pbp_df['drive'].astype(str)
    pbp_df.loc[:, 'GameDrive'] = pbp_df['game_id'].astype(str) + "-" + pbp_df['drive'].astype(str)


    # Group by splits and compute statistics
    # This is a simple example to compute 'Attempts', more columns can be added similarly
    result = pbp_df.groupby(splits).agg(
        Player_Name = pd.NamedAgg(column='passer_player_name', aggfunc=find_player_name),
        Attempts = pd.NamedAgg(column='pass_attempt', aggfunc='count'),
        Completions = pd.NamedAgg(column='complete_pass', aggfunc='sum'),
        Drives = pd.NamedAgg(column='GameDrive', aggfunc='nunique'),
        Total_Yards = pd.NamedAgg(column='yards_gained', aggfunc='sum'),
        Total_Yards_8 = pd.NamedAgg(column='yards_gained', aggfunc=lambda x: sum([y if g > 8 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        Total_Yards_4 = pd.NamedAgg(column='yards_gained', aggfunc=lambda x: sum([y if g > 12 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        Total_Raw_AirYards = pd.NamedAgg(column='air_yards', aggfunc='sum'),
        Total_Comp_AirYards = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: (x * pbp_df.loc[x.index, 'air_yards']).sum()),
        TimesHit = pd.NamedAgg(column='qb_hit', aggfunc='sum'),
        Interceptions = pd.NamedAgg(column='interception', aggfunc='sum'),
        Interceptions_8 = pd.NamedAgg(column='interception', aggfunc=lambda x: sum([y if g > 8 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        Interceptions_4 = pd.NamedAgg(column='interception', aggfunc=lambda x: sum([y if g > 12 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        TDs = pd.NamedAgg(column='touchdown', aggfunc='sum'),
        TDs_8 = pd.NamedAgg(column='touchdown', aggfunc=lambda x: sum([y if g > 8 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        TDs_4 = pd.NamedAgg(column='touchdown', aggfunc=lambda x: sum([y if g > 12 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        Air_TDs = pd.NamedAgg(column='touchdown', aggfunc=lambda x: ((pbp_df.loc[x.index, 'yards_after_catch'] == 0).astype(int) * x).sum()),
        Total_EPA = pd.NamedAgg(column='epa', aggfunc='sum'),
        Success_Rate = pd.NamedAgg(column='epa', aggfunc=lambda x: (x > 0).sum() / len(x)),
        EPA_Per_Comp = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: (x * pbp_df.loc[x.index, 'epa']).sum() / x.sum() if x.sum() != 0 else 0),
        EPA_Comp_Perc = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: (x * pbp_df.loc[x.index, 'epa']).sum() / abs(pbp_df.loc[x.index, 'epa']).sum()),
        Total_WPA = pd.NamedAgg(column='wpa', aggfunc='sum'),
        Win_Success_Rate = pd.NamedAgg(column='wpa', aggfunc=lambda x: (x > 0).sum() / len(x)),
        WPA_per_Comp = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: (x * pbp_df.loc[x.index, 'wpa']).sum() / x.sum() if x.sum() != 0 else 0),
        WPA_Comp_Perc = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: (x * pbp_df.loc[x.index, 'wpa']).sum() / abs(pbp_df.loc[x.index, 'wpa']).sum() if abs(pbp_df.loc[x.index, 'wpa']).sum() != 0 else 0),
        Total_Clutch_EPA = pd.NamedAgg(column='epa', aggfunc=lambda x: (x * abs(pbp_df.loc[x.index, 'wpa'])).sum()),
        airEPA_Comp = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: (x * pbp_df.loc[x.index, 'air_epa']).sum()),
        airEPA_Incomp = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: (pbp_df.loc[x.index, 'air_epa'] * (x == 0)).sum()),
        Total_Raw_airEPA = pd.NamedAgg(column='air_epa', aggfunc='sum'),
        air_Success_Rate = pd.NamedAgg(column='air_epa', aggfunc=lambda x: (x > 0).sum() / len(x)),
        air_Comp_Success_Rate = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: ((x * pbp_df.loc[x.index, 'air_epa']) > 0).sum() / len(x)),
        airWPA_Comp = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: (x * pbp_df.loc[x.index, 'air_wpa']).sum()),
        airWPA_Incomp = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: (pbp_df.loc[x.index, 'air_wpa'] * (x == 0)).sum()),
        Total_Raw_airWPA = pd.NamedAgg(column='air_wpa', aggfunc='sum'),
        air_Win_Success_Rate = pd.NamedAgg(column='air_wpa', aggfunc=lambda x: (x > 0).sum() / len(x)),
        air_Comp_Win_Success_Rate = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: ((x * pbp_df.loc[x.index, 'air_wpa']) > 0).sum() / len(x)),
        yacEPA_Comp = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: (x * pbp_df.loc[x.index, 'yac_epa']).sum()),
        yacEPA_Drop = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: (pbp_df.loc[x.index, 'yac_epa'] * (x == 0)).sum()),
        Total_yacEPA = pd.NamedAgg(column='yac_epa', aggfunc='sum'),
        yacWPA_Comp = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: (x * pbp_df.loc[x.index, 'yac_wpa']).sum()),
        yacWPA_Drop = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: (pbp_df.loc[x.index, 'yac_wpa'] * (x == 0)).sum()),
        Total_yacWPA = pd.NamedAgg(column='yac_wpa', aggfunc='sum'),
        yac_Success_Rate = pd.NamedAgg(column='yac_epa', aggfunc=lambda x: (x > 0).sum() / len(x)),
        yac_Rec_Success_Rate = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: ((x * pbp_df.loc[x.index, 'yac_epa']) > 0).sum() / len(x)),
        yac_Win_Success_Rate = pd.NamedAgg(column='yac_wpa', aggfunc=lambda x: (x > 0).sum() / len(x)),
        yac_Complete_Win_Success_Rate = pd.NamedAgg(column='complete_pass', aggfunc=lambda x: ((x * pbp_df.loc[x.index, 'yac_wpa']) > 0).sum() / len(x)),
    )

    # Additional calculations can be performed on the result DataFrame
    result['Comp_Perc'] = result['Completions'] / result['Attempts']
    result['Yards_Per_Att'] = result['Total_Yards'] / result['Attempts']
    result['Yards_Per_Comp'] = result['Total_Yards'] / result['Completions']
    result['Yards_Per_Drive'] = result['Total_Yards'] / result['Drives']
    result['Raw_AirYards_per_Att'] = result['Total_Raw_AirYards'] / result['Attempts']
    result['Comp_AirYards_per_Att'] = result['Total_Comp_AirYards'] / result['Attempts']
    result['Raw_AirYards_per_Comp'] = result['Total_Raw_AirYards'] / result['Completions']
    result['Comp_AirYards_per_Comp'] = result['Total_Comp_AirYards'] / result['Completions']
    result['Raw_AirYards_per_Drive'] = result['Total_Raw_AirYards'] / result['Drives']
    result['Comp_AirYards_per_Drive'] = result['Total_Comp_AirYards'] / result['Drives']
    result['PACR'] = result['Total_Yards'] / result['Total_Raw_AirYards']
    result['TimesHit_per_Drive'] = result['TimesHit'] / result['Drives']
    result['aPACR'] = (result['Total_Yards'] + (20 * result['TDs']) - (45 * result['Interceptions'])) / result['Total_Raw_AirYards']
    result['Air_TD_Rate'] = result['Air_TDs'] / result['TDs']
    result['TD_to_Int'] = result['TDs'] / result['Interceptions']
    result['EPA_per_Att'] = result['Total_EPA'] / result['Attempts']
    result['TD_per_Att'] = result['TDs'] / result['Attempts']
    result['Air_TD_per_Att'] = result['Air_TDs'] / result['Attempts']
    result['Int_per_Att'] = result['Interceptions'] / result['Attempts']
    result['TD_per_Comp'] = result['TDs'] / result['Completions']
    result['Air_TD_per_Comp'] = result['Air_TDs'] / result['Completions']
    result['TD_per_Drive'] = result['TDs'] / result['Drives']
    result['Air_TD_per_Drive'] = result['Air_TDs'] / result['Drives']
    result['Int_per_Drive'] = result['Interceptions'] / result['Drives']
    result['EPA_per_Drive'] = result['Total_EPA'] / result['Drives']
    result['WPA_per_Att'] = result['Total_WPA'] / result['Attempts']
    result['WPA_per_Drive'] = result['Total_WPA'] / result['Drives']
    result['Clutch_EPA_per_Att'] = result['Total_Clutch_EPA'] / result['Attempts']
    result['Clutch_EPA_per_Drive'] = result['Total_Clutch_EPA'] / result['Drives']
    result['Raw_airEPA_per_Att'] = result['Total_Raw_airEPA'] / result['Attempts']
    result['Raw_airEPA_per_Drive'] = result['Total_Raw_airEPA'] / result['Drives']
    result['epa_PACR'] = result['Total_EPA'] / result['Total_Raw_airEPA']
    result['airEPA_per_Att'] = result['airEPA_Comp'] / result['Attempts']
    result['airEPA_per_Comp'] = result['airEPA_Comp'] / result['Completions']
    result['airEPA_per_Drive'] = result['airEPA_Comp'] / result['Drives']
    result['wpa_PACR'] = result['Total_WPA'] / result['Total_Raw_airWPA']
    result['Raw_airWPA_per_Att'] = result['Total_Raw_airWPA'] / result['Attempts']
    result['Raw_airWPA_per_Drive'] = result['Total_Raw_airWPA'] / result['Drives']
    result['airWPA_per_Att'] = result['airWPA_Comp'] / result['Attempts']
    result['airWPA_per_Comp'] = result['airWPA_Comp'] / result['Completions']
    result['airWPA_per_Drive'] = result['airWPA_Comp'] / result['Drives']
    result['yacEPA_per_Att'] = result['Total_yacEPA'] / result['Attempts']
    result['yacEPA_per_Comp'] = result['yacEPA_Comp'] / result['Completions']
    result['yacEPA_Rec_per_Drive'] = result['yacEPA_Comp'] / result['Drives']
    result['yacEPA_Drop_per_Drive'] = result['yacEPA_Drop'] / result['Drives']

    return result.reset_index()

def calc_rushing_splits(splits, pbp_df):
    pbp_df = pbp_df.copy()

    # Filter to only rush attempts:
    pbp_df = pbp_df[(pbp_df['rush_attempt'] == 1) & (pbp_df['play_type'] != "No Play")]
    pbp_df['GameDrive'] = pbp_df['game_id'].astype(str) + "-" + pbp_df['drive'].astype(str)

    # Aggregate calculations
    result = pbp_df.groupby(splits).agg(
        Player_Name=('rusher_player_name', find_player_name),
        Carries=('rush_attempt', 'count'),
        Drives=('GameDrive', 'nunique'),
        Total_Yards=('yards_gained', 'sum'),
        Total_Yards_8=('yards_gained', lambda x: sum([y if g > 8 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        Total_Yards_4=('yards_gained', lambda x: sum([y if g > 12 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        Fumbles=('fumble', 'sum'),
        TDs=('touchdown', 'sum'),
        TDs_8=('touchdown', lambda x: sum([y if g > 8 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        TDs_4=('touchdown', lambda x: sum([y if g > 12 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        Total_EPA=('epa', 'sum'),
        Success_Rate=('epa', lambda x: (x > 0).sum() / len(x)),
        EPA_Ratio=('epa', lambda x: (x > 0).sum() / abs(x).sum() if abs(x).sum() != 0 else 0),
        Total_WPA=('wpa', 'sum'),
        Win_Success_Rate=('wpa', lambda x: (x > 0).sum() / len(x)),
        WPA_Ratio=('wpa', lambda x: (x > 0).sum() / abs(x).sum() if abs(x).sum() != 0 else 0),
        Total_Clutch_EPA=('epa', lambda x: (x * abs(pbp_df.loc[x.index, 'wpa'])).sum()),
    )

    # Derived calculations
    result['Car_per_Drive'] = result['Carries'] / result['Drives']
    result['Yards_per_Car'] = result['Total_Yards'] / result['Carries']
    result['Yards_per_Drive'] = result['Total_Yards'] / result['Drives']
    result['TD_to_Fumbles'] = result.apply(lambda row: row['TDs'] / row['Fumbles'] if row['Fumbles'] != 0 else 0, axis=1)
    result['EPA_per_Car'] = result['Total_EPA'] / result['Carries']
    result['TD_per_Car'] = result['TDs'] / result['Carries']
    result['Fumbles_per_Car'] = result['Fumbles'] / result['Carries']
    result['Fumbles_per_Drive'] = result['Fumbles'] / result['Drives']
    result['TD_Drive'] = result['TDs'] / result['Drives']
    result['EPA_per_Drive'] = result['Total_EPA'] / result['Drives']
    result['WPA_per_Drive'] = result['Total_WPA'] / result['Drives']
    result['WPA_per_Car'] = result['Total_WPA'] / result['Carries']
    result['Clutch_EPA_per_Car'] = result['Total_Clutch_EPA'] / result['Carries']
    result['Clutch_EPA_per_Drive'] = result['Total_Clutch_EPA'] / result['Drives']

    return result.reset_index()

def calc_receiving_splits(splits, pbp_df):
    pbp_df = pbp_df.copy()

    # Filter to only pass attempts:
    pbp_df = pbp_df[(pbp_df['pass_attempt'] == 1) & (pbp_df['play_type'] != "No Play")]
    pbp_df['GameDrive'] = pbp_df['game_id'].astype(str) + "-" + pbp_df['drive'].astype(str)

    # Aggregate calculations
    result = pbp_df.groupby(splits).agg(
        Player_Name=('receiver_player_name', find_player_name),
        Targets=('pass_attempt', 'count'),
        Receptions=('complete_pass', 'sum'),
        Receptions_8=('complete_pass', lambda x: sum([y if g > 8 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        Receptions_4=('complete_pass', lambda x: sum([y if g > 12 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        Drives=('GameDrive', 'nunique'),
        Total_Yards=('yards_gained', 'sum'),
        Total_Yards_8=('yards_gained', lambda x: sum([y if g > 8 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        Total_Yards_4=('yards_gained', lambda x: sum([y if g > 12 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        Total_Raw_YAC=('yards_after_catch', 'sum'),
        Total_Caught_YAC=('yards_after_catch', lambda x: (pbp_df.loc[x.index, 'complete_pass'] * x).sum()),
        Total_Dropped_YAC=('yards_after_catch', lambda x: ((pbp_df.loc[x.index, 'complete_pass'] == 0).astype(int) * x).sum()),
        Fumbles=('fumble', 'sum'),
        TDs=('touchdown', 'sum'),
        TDs_8=('touchdown', lambda x: sum([y if g > 8 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        TDs_4=('touchdown', lambda x: sum([y if g > 12 else 0 for y, g in zip(x, pbp_df.loc[x.index, 'game_number'])])),
        AC_TDs=('touchdown', lambda x: ((pbp_df.loc[x.index, 'yards_after_catch'] > 0).astype(int) * x).sum()),
        Total_EPA=('epa', 'sum'),
        Success_Rate=('epa', lambda x: (x > 0).sum() / pbp_df.loc[x.index, 'pass_attempt'].sum()),
        EPA_per_Rec=('epa', lambda x: (pbp_df.loc[x.index, 'complete_pass'] * x).sum() / pbp_df.loc[x.index, 'complete_pass'].sum() if pbp_df.loc[x.index, 'complete_pass'].sum() != 0 else 0),
        EPA_Rec_Perc=('epa', lambda x: (pbp_df.loc[x.index, 'complete_pass'] * x).sum() / abs(x).sum()),
        Total_WPA=('wpa', 'sum'),
        Win_Success_Rate=('wpa', lambda x: (x > 0).sum() / pbp_df.loc[x.index, 'pass_attempt'].sum()),
        WPA_per_Rec=('wpa', lambda x: (pbp_df.loc[x.index, 'complete_pass'] * x).sum() / pbp_df.loc[x.index, 'complete_pass'].sum() if pbp_df.loc[x.index, 'complete_pass'].sum() != 0 else 0),
        WPA_Rec_Perc=('wpa', lambda x: (pbp_df.loc[x.index, 'complete_pass'] * x).sum() / abs(x).sum() if abs(x).sum() != 0 else 0),
        Total_Clutch_EPA=('epa', lambda x: (x * abs(pbp_df.loc[x.index, 'wpa'])).sum()),
        Total_Raw_AirYards=('air_yards', 'sum'),
        Total_Caught_AirYards=('air_yards', lambda x: (pbp_df.loc[x.index, 'complete_pass'] * x).sum()),
        Total_Raw_airEPA=('air_epa', 'sum'),
        Total_Caught_airEPA=('air_epa', lambda x: (pbp_df.loc[x.index, 'complete_pass'] * x).sum()),
        Total_Raw_airWPA=('air_wpa', 'sum'),
        Total_Caught_airWPA=('air_wpa', lambda x: (pbp_df.loc[x.index, 'complete_pass'] * x).sum()),
        yacEPA_Rec=('yac_epa', lambda x: (pbp_df.loc[x.index, 'complete_pass'] * x).sum()),
        yacEPA_Drop=('yac_epa', lambda x: ((pbp_df.loc[x.index, 'complete_pass'] == 0).astype(int) * x).sum()),
        Total_yacEPA=('yac_epa', 'sum'),
        yacWPA_Rec=('yac_wpa', lambda x: (pbp_df.loc[x.index, 'complete_pass'] * x).sum()),
        yacWPA_Drop=('yac_wpa', lambda x: ((pbp_df.loc[x.index, 'complete_pass'] == 0).astype(int) * x).sum()),
        Total_yacWPA=('yac_wpa', 'sum'),
        yac_Success_Rate = ('yac_epa', lambda x: (x > 0).sum() / len(x)),
        yac_Rec_Success_Rate = ('complete_pass', lambda x: ((x * pbp_df.loc[x.index, 'yac_epa']) > 0).sum() / len(x)),
        air_Success_Rate = ('air_epa', lambda x: (x > 0).sum() / len(x)),
        air_Rec_Success_Rate = ('complete_pass', lambda x: ((x * pbp_df.loc[x.index, 'air_epa']) > 0).sum() / len(x)),
        yac_Win_Success_Rate = ('yac_wpa', lambda x: (x > 0).sum() / len(x)),
        yac_Rec_Win_Success_Rate = ('complete_pass', lambda x: ((x * pbp_df.loc[x.index, 'yac_wpa']) > 0).sum() / len(x)),
        air_Win_Success_Rate = ('air_wpa', lambda x: (x > 0).sum() / len(x)),
        air_Rec_Win_Success_Rate = ('complete_pass', lambda x: ((x * pbp_df.loc[x.index, 'air_wpa']) > 0).sum() / len(x)),
    )

    # Derived calculations
    result['Targets_per_Drive'] = result['Targets'] / result['Drives']
    result['Rec_per_Drive'] = result['Receptions'] / result['Drives']
    result['Yards_per_Drive'] = result['Total_Yards'] / result['Drives']
    result['Yards_per_Rec'] = result['Total_Yards'] / result['Receptions']
    result['Yards_per_Target'] = result['Total_Yards'] / result['Targets']
    result['YAC_per_Target'] = result['Total_Raw_YAC'] / result['Targets']
    result['Caught_YAC_per_Target'] = result['Total_Caught_YAC'] / result['Targets']
    result['Dropped_YAC_per_Target'] = result['Total_Dropped_YAC'] / result['Targets']
    result['YAC_per_Rec'] = result['Total_Raw_YAC'] / result['Receptions']
    result['Caught_YAC_per_Rec'] = result['Total_Caught_YAC'] / result['Receptions']
    result['Dropped_YAC_per_Rec'] = result['Total_Dropped_YAC'] / result['Receptions']
    result['YAC_per_Drive'] = result['Total_Raw_YAC'] / result['Drives']
    result['Caught_YAC_per_Drive'] = result['Total_Caught_YAC'] / result['Drives']
    result['Dropped_YAC_per_Drive'] = result['Total_Dropped_YAC'] / result['Drives']
    result['Rec_Percentage'] = result['Receptions'] / result['Targets']
    result['TDs_per_Drive'] = result['TDs'] / result['Drives']
    result['Fumbles_per_Drive'] = result['Fumbles'] / result['Drives']
    result['AC_TDs_per_Drive'] = result['AC_TDs'] / result['Drives']
    result['AC_TD_Rate'] = result['AC_TDs'] / result['TDs']
    result['TD_to_Fumbles'] = result['TDs'] / result['Fumbles']
    result['EPA_per_Drives'] = result['Total_EPA'] / result['Drives']
    result['EPA_per_Target'] = result['Total_EPA'] / result['Targets']
    result['TD_per_Targets'] = result['TDs'] / result['Targets']
    result['Fumbles_per_Receptions'] = result['Fumbles'] / result['Receptions']
    result['TD_per_Rec'] = result['TDs'] / result['Receptions']
    result['WPA_per_Drive'] = result['Total_WPA'] / result['Drives']
    result['WPA_per_Target'] = result['Total_WPA'] / result['Targets']
    result['Clutch_EPA_per_Drive'] = result['Total_Clutch_EPA'] / result['Drives']
    result['PACR'] = result['Total_Yards'] / result['Total_Raw_AirYards']
    result['Raw_AirYards_per_Target'] = result['Total_Raw_AirYards'] / result['Targets']
    result['RACR'] = result['Total_Yards'] / result['Total_Raw_AirYards']
    result['Raw_airEPA_per_Drive'] = result['Total_Raw_airEPA'] / result['Drives']
    result['Caught_airEPA_per_Drive'] = result['Total_Caught_airEPA'] / result['Drives']
    result['airEPA_per_Target'] = result['Total_Raw_airEPA'] / result['Targets']
    result['Caught_airEPA_per_Target'] = result['Total_Caught_airEPA'] / result['Targets']
    result['epa_RACR'] = result['Total_EPA'] / result['Total_Raw_airEPA']
    result['Raw_airWPA_per_Drive'] = result['Total_Raw_airWPA'] / result['Drives']
    result['Caught_airWPA_per_Drive'] = result['Total_Caught_airWPA'] / result['Drives']
    result['airWPA_per_Target'] = result['Total_Raw_airWPA'] / result['Targets']
    result['Caught_airWPA_per_Target'] = result['Total_Caught_airWPA'] / result['Targets']
    result['yacEPA_per_Target'] = result['Total_yacEPA'] / result['Targets']
    result['yacEPA_per_Rec'] = result['yacEPA_Rec'] / result['Receptions']
    result['yacEPA_Rec_per_Drive'] = result['yacEPA_Rec'] / result['Drives']
    result['yacEPA_Drop_per_Drive'] = result['yacEPA_Drop'] / result['Drives']
    result['yacWPA_per_Target'] = result['Total_yacWPA'] / result['Targets']
    result['yacWPA_per_Rec'] = result['yacWPA_Rec'] / result['Receptions']
    result['yacWPA_Rec_per_Drive'] = result['yacWPA_Rec'] / result['Drives']
    result['yacWPA_Drop_per_Drive'] = result['yacWPA_Drop'] / result['Drives']
    result['wpa_RACR'] = result['Total_WPA'] / result['Total_Raw_airWPA']

    return result.reset_index()

In [4]:
pbps = {}
for year in range(2009, 2023):
    selected_data = load_pbp(year)
    # Adding the 'Season' column
    selected_data['Season'] = year
    pbps[year] = selected_data

data loaded from redis for 2009
data loaded from redis for 2010
data loaded from redis for 2011
data loaded from redis for 2012
data loaded from redis for 2013
data loaded from redis for 2014
data loaded from redis for 2015
data loaded from redis for 2016
data loaded from redis for 2017
data loaded from redis for 2018
data loaded from redis for 2019
data loaded from redis for 2020
data loaded from redis for 2021
data loaded from redis for 2022

In [5]:
pbp_data = pd.concat(pbps.values(), ignore_index=True)

In [6]:
pbp_data

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,offense_formation,offense_personnel,defenders_in_box,defense_personnel,number_of_pass_rushers,players_on_play,offense_players,defense_players,n_offense,n_defense
0,1.0,2009_01_BUF_NE,2009091400,NE,BUF,REG,1,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,56.0,2009_01_BUF_NE,2009091400,NE,BUF,REG,1,NE,home,BUF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,79.0,2009_01_BUF_NE,2009091400,NE,BUF,REG,1,NE,home,BUF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,101.0,2009_01_BUF_NE,2009091400,NE,BUF,REG,1,NE,home,BUF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,122.0,2009_01_BUF_NE,2009091400,NE,BUF,REG,1,NE,home,BUF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679720,4035.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,None,None,None,...,None,None,NaN,None,NaN,,,,0.0,0.0
679721,4024.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,KC,away,PHI,...,None,None,NaN,None,NaN,40994;46152;52618;54026;54478;53552;53492;5454...,,,0.0,0.0
679722,4050.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,PHI,home,KC,...,None,None,NaN,None,NaN,48259;54724;54568;54600;54026;53579;45102;4251...,,,0.0,0.0
679723,4072.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,PHI,home,KC,...,SHOTGUN,"1 RB, 1 TE, 3 WR",3.0,"0 DL, 4 LB, 7 DB",5.0,52608;52546;48259;46118;47846;43368;54568;5460...,,,0.0,0.0
679724,4094.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,None,None,None,...,None,None,NaN,None,NaN,,,,0.0,0.0

In [7]:
pbp_data = pbp_data[pbp_columns]

In [8]:
pbp_data

,pass_attempt,passer_player_id,rusher_player_id,receiver_player_id,play_type,game_id,drive,passer_player_name,complete_pass,yards_gained,...,air_wpa,yac_epa,yac_wpa,rush_attempt,rusher_player_name,fumble,receiver_player_name,posteam,defteam,Season
0,NaN,None,None,None,None,2009_01_BUF_NE,NaN,None,NaN,NaN,...,NaN,NaN,NaN,NaN,None,NaN,None,None,None,2009
1,0.0,None,None,None,kickoff,2009_01_BUF_NE,1.0,None,0.0,0.0,...,NaN,NaN,NaN,0.0,None,0.0,None,NE,BUF,2009
2,1.0,00-0019596,None,00-0011754,pass,2009_01_BUF_NE,1.0,T.Brady,0.0,0.0,...,0.0,-0.013064,-0.017915,0.0,None,0.0,R.Moss,NE,BUF,2009
3,0.0,None,00-0016098,None,run,2009_01_BUF_NE,1.0,None,0.0,3.0,...,NaN,NaN,NaN,1.0,F.Taylor,0.0,None,NE,BUF,2009
4,1.0,00-0019596,None,00-0005091,pass,2009_01_BUF_NE,1.0,T.Brady,1.0,6.0,...,0.0,0.840862,0.004928,0.0,None,0.0,K.Faulk,NE,BUF,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679720,0.0,None,None,None,no_play,2022_22_KC_PHI,17.0,None,0.0,0.0,...,NaN,NaN,NaN,0.0,None,0.0,None,None,None,2022
679721,0.0,None,None,None,field_goal,2022_22_KC_PHI,17.0,None,0.0,0.0,...,NaN,NaN,NaN,0.0,None,0.0,None,KC,PHI,2022
679722,0.0,None,None,None,kickoff,2022_22_KC_PHI,18.0,None,0.0,0.0,...,NaN,NaN,NaN,0.0,None,0.0,None,PHI,KC,2022
679723,1.0,00-0036389,None,None,pass,2022_22_KC_PHI,18.0,J.Hurts,0.0,0.0,...,0.0,-2.089092,-0.127170,0.0,None,0.0,None,PHI,KC,2022
679724,NaN,None,None,None,None,2022_22_KC_PHI,18.0,None,NaN,NaN,...,NaN,NaN,NaN,NaN,None,NaN,None,None,None,2022

In [9]:
pbp_data = pbp_data.sort_values(by='Season')
pbp_data['game'] = pbp_data.groupby('Season')['game_id'].transform(lambda x: x.nunique()).cumsum()

# Arrange by Season and game_id, and group by Season, game_id, and posteam
pbp_data = pbp_data.sort_values(by=['Season', 'game_id'])
pbp_data['var_temp'] = pbp_data.groupby(['Season', 'game_id', 'posteam']).cumcount() + 1
pbp_data['var_temp'] = pbp_data['var_temp'].apply(lambda x: 1 if x == 1 else 0)

# Group by Season and posteam
pbp_data['game_number'] = pbp_data.groupby(['Season', 'posteam'])['var_temp'].cumsum()
pbp_data['max'] = pbp_data.groupby(['Season', 'posteam'])['game_number'].transform('max')

pbp_data['posteam'] = pbp_data['posteam'].apply(lambda x: 'JAC' if x == 'JAX' else x)
pbp_data['defteam'] = pbp_data['defteam'].apply(lambda x: 'JAC' if x == 'JAX' else x)

In [10]:
# First generate stats at the Season level for each player,
# removing the observations with missing player names:
season_passing_df = calc_passing_splits(["Season", "passer_player_id"], pbp_data)
season_passing_df['passer_gsis'] = season_passing_df['passer_player_id']

# Filter out rows where 'passer_player_id' is 'None'
season_passing_df = season_passing_df[season_passing_df['passer_player_id'] != 'None']

# Sort the dataframe by 'Season' and 'Attempts' in descending order
season_passing_df = season_passing_df.sort_values(by=['Season', 'Attempts'], ascending=[True, False])

In [11]:
print(season_passing_df.head(25))

     Season passer_player_id       Player_Name  Attempts  Completions  Drives  \
11     2009       00-0010346         P.Manning       714        480.0     173
36     2009       00-0021678            T.Romo       662        392.0     186
58     2009       00-0023459         A.Rodgers       642        378.0     177
25     2009       00-0020531           D.Brees       640        435.0     183
7      2009       00-0005106           B.Favre       639        407.0     181
20     2009       00-0019596           T.Brady       629        394.0     174
47     2009       00-0022787          M.Schaub       611        396.0     164
16     2009       00-0017200          K.Warner       599        386.0     173
72     2009       00-0024226          J.Cutler       591        336.0     173
95     2009       00-0026158          J.Flacco       582        339.0     175
62     2009       00-0023541           K.Orton       571        336.0     168
33     2009       00-0021231         D.Garrard       558        314.0     157
51     2009       00-0022924  B.Roethlisberger       556        337.0     157
52     2009       00-0022942          P.Rivers       553        344.0     154
59     2009       00-0023460        J.Campbell       549        327.0     153
48     2009       00-0022803         E.Manning       539        317.0     159
64     2009       00-0023662          M.Cassel       537        272.0     171
35     2009       00-0021429          C.Palmer       533        300.0     164
13     2009       00-0011022          D.McNabb       522        286.0     161
9      2009       00-0007091      M.Hasselbeck       521        293.0     150
99     2009       00-0026197           C.Henne       479        274.0     136
94     2009       00-0026143            M.Ryan       471        263.0     131
105    2009       00-0026898         M.Sanchez       463        237.0     184
103    2009       00-0026498        M.Stafford       402        201.0     112
54     2009       00-0023436           A.Smith       394        225.0     118

     Total_Yards  Total_Yards_8  Total_Yards_4  Total_Raw_AirYards  ...  \
11        5352.0         2854.0         1741.0              6068.0  ...
36        4671.0         2544.0         1497.0              4541.0  ...
58        4549.0         2517.0         1415.0              5405.0  ...
25        4972.0         2714.0         1535.0              4964.0  ...
7         4479.0         2681.0         1516.0              4844.0  ...
20        4446.0         2136.0          888.0              4993.0  ...
47        4619.0         2365.0         1307.0              4444.0  ...
16        4158.0         2104.0         1283.0              4352.0  ...
72        3467.0         1532.0          811.0              4562.0  ...
95        3606.0         1673.0          897.0              4630.0  ...
62        3643.0         1878.0         1118.0              3806.0  ...
33        3366.0         1595.0          702.0              4224.0  ...
51        3980.0         1851.0         1052.0              4548.0  ...
52        4370.0         2244.0         1205.0              5066.0  ...
59        3343.0         1814.0          801.0              3337.0  ...
48        3805.0         2005.0         1002.0              4515.0  ...
64        2676.0         1569.0          904.0              3972.0  ...
35        2993.0         1241.0          615.0              4120.0  ...
13        3500.0         2403.0         1261.0              4210.0  ...
9         2820.0         1587.0          800.0              3351.0  ...
99        2702.0         1831.0          988.0              3778.0  ...
94        2824.0         1098.0          600.0              3746.0  ...
105       2785.0         1469.0          905.0              4062.0  ...
103       2100.0          935.0            0.0              3045.0  ...
54        2216.0         1578.0          722.0              2543.0  ...

     Raw_airWPA_per_Att  Raw_airWPA_per_Drive  airWPA_per_Att  \
11             0.003553              0.014662        0.003390
36             0.002644              0.009409        0.002713
58             0.000909              0.003297        0.001826
25             0.000435              0.001521        0.002063
7              0.002104              0.007427        0.001864
20             0.001278              0.004621        0.001850
47             0.002565              0.009557        0.002505
16            -0.000870             -0.003013        0.000444
72             0.002982              0.010186        0.003350
95             0.004691              0.015601        0.004261
62             0.002254              0.007661        0.003419
33             0.004336              0.015410        0.004267
51             0.000958              0.003393        0.003274
52             0.003071              0.011026        0.005242
59             0.004772              0.017125        0.002326
48             0.003512              0.011906        0.003820
64             0.006194              0.019450        0.006706
35             0.004807              0.015624        0.005799
13             0.003180              0.010309        0.003219
9              0.002910              0.010107        0.003064
99             0.003813              0.013430        0.004764
94             0.005425              0.019504        0.005465
105            0.001274              0.003205        0.002801
103            0.006047              0.021704        0.005614
54             0.002271              0.007584        0.002314

     airWPA_per_Comp  airWPA_per_Drive  yacEPA_per_Att  yacEPA_per_Comp  \
11          0.005043          0.013992       -0.237633         0.662315
36          0.004582          0.009656       -0.156429         0.738429
58          0.003102          0.006625       -0.245889         0.714252
25          0.003036          0.007217       -0.073830         0.651044
7           0.002927          0.006582       -0.125331         0.694797
20          0.002953          0.006686       -0.233077         0.721300
47          0.003865          0.009332       -0.139287         0.654147
16          0.000689          0.001538       -0.199728         0.586709
72          0.005893          0.011445       -0.540204         0.534861
95          0.007316          0.014172       -0.356046         0.624158
62          0.005811          0.011621       -0.237563         0.709357
33          0.007583          0.015165       -0.328685         0.598506
51          0.005402          0.011596       -0.260999         0.640410
52          0.008427          0.018824       -0.287622         0.709367
59          0.003905          0.008346       -0.054552         0.814962
48          0.006495          0.012950       -0.312798         0.620102
64          0.013239          0.021058       -0.477452         0.518956
35          0.010304          0.018848       -0.393405         0.579858
13          0.005876          0.010438       -0.360482         0.639842
9           0.005449          0.010643       -0.357171         0.641019
99          0.008329          0.016781       -0.445623         0.535305
94          0.009787          0.019648       -0.407344         0.593279
105         0.005473          0.007049       -0.704387         0.566839
103         0.011228          0.020150       -0.525189         0.765722
54          0.004052          0.007726       -0.271131         0.656334

     yacEPA_Rec_per_Drive  yacEPA_Drop_per_Drive  passer_gsis
11               1.837638              -2.818388   00-0010346
36               1.556259              -2.113011   00-0021678
58               1.525352              -2.417220   00-0023459
25               1.547563              -1.805766   00-0020531
7                1.562333              -2.004800   00-0005106
20               1.633289              -2.475848   00-0019596
47               1.579526              -2.098456   00-0022787
16               1.309073              -2.000617   00-0017200
72               1.038805              -2.884242   00-0024226
95               1.209083              -2.393190   00-0026158
62               1.418715              -2.226146   00-0023541
33               1.197012              -2.365204   00-0021231
51               1.374639              -2.298941   00-0022924
52               1.584560              -2.617386   00-0022942
59               1.741782              -1.937527   00-0023460
48               1.236305              -2.296671   00-0022803
64               0.825474              -2.324842   00-0023662
35               1.060715              -2.339280   00-0021429
13               1.136614              -2.305382   00-0011022
9                1.252123              -2.492696   00-0007091
99               1.078482              -2.647994   00-0026197
94               1.191087              -2.655658   00-0026143
105              0.730114              -2.502567   00-0026898
103              1.374197              -3.259249   00-0026498
54               1.251485              -2.156785   00-0023436

[25 rows x 94 columns]

In [12]:
### Now do the rushing stats
season_rushing_df = calc_rushing_splits(["Season", "rusher_player_id"], pbp_data)

# Filter out rows where 'rusher_player_id' is 'None'
season_rushing_df = season_rushing_df[season_rushing_df['rusher_player_id'] != 'None']

# Sort the dataframe by Season and Carries in descending order
season_rushing_df = season_rushing_df.sort_values(by=['Season', 'Carries'], ascending=[True, False])

In [13]:
### Now do the receiving stats
season_receiving_df = calc_receiving_splits(["Season", "receiver_player_id"], pbp_data)
season_receiving_df['receiver_gsis'] = season_receiving_df['receiver_player_id']

# Filter out rows where receiver_player_id is 'None'
season_receiving_df = season_receiving_df[season_receiving_df['receiver_player_id'] != 'None']

# Sort the dataframe by 'Season' and 'Targets' in descending order
season_receiving_df = season_receiving_df.sort_values(by=['Season', 'Targets'], ascending=[True, False])

In [14]:
season_passing_df.columns

Index(['Season', 'passer_player_id', 'Player_Name', 'Attempts', 'Completions',
       'Drives', 'Total_Yards', 'Total_Yards_8', 'Total_Yards_4',
       'Total_Raw_AirYards', 'Total_Comp_AirYards', 'TimesHit',
       'Interceptions', 'Interceptions_8', 'Interceptions_4', 'TDs', 'TDs_8',
       'TDs_4', 'Air_TDs', 'Total_EPA', 'Success_Rate', 'EPA_Per_Comp',
       'EPA_Comp_Perc', 'Total_WPA', 'Win_Success_Rate', 'WPA_per_Comp',
       'WPA_Comp_Perc', 'Total_Clutch_EPA', 'airEPA_Comp', 'airEPA_Incomp',
       'Total_Raw_airEPA', 'air_Success_Rate', 'air_Comp_Success_Rate',
       'airWPA_Comp', 'airWPA_Incomp', 'Total_Raw_airWPA',
       'air_Win_Success_Rate', 'air_Comp_Win_Success_Rate', 'yacEPA_Comp',
       'yacEPA_Drop', 'Total_yacEPA', 'yacWPA_Comp', 'yacWPA_Drop',
       'Total_yacWPA', 'yac_Success_Rate', 'yac_Rec_Success_Rate',
       'yac_Win_Success_Rate', 'yac_Complete_Win_Success_Rate', 'Comp_Perc',
       'Yards_Per_Att', 'Yards_Per_Comp', 'Yards_Per_Drive',
       'Raw_AirYards_per_Att', 'Comp_AirYards_per_Att',
       'Raw_AirYards_per_Comp', 'Comp_AirYards_per_Comp',
       'Raw_AirYards_per_Drive', 'Comp_AirYards_per_Drive', 'PACR',
       'TimesHit_per_Drive', 'aPACR', 'Air_TD_Rate', 'TD_to_Int',
       'EPA_per_Att', 'TD_per_Att', 'Air_TD_per_Att', 'Int_per_Att',
       'TD_per_Comp', 'Air_TD_per_Comp', 'TD_per_Drive', 'Air_TD_per_Drive',
       'Int_per_Drive', 'EPA_per_Drive', 'WPA_per_Att', 'WPA_per_Drive',
       'Clutch_EPA_per_Att', 'Clutch_EPA_per_Drive', 'Raw_airEPA_per_Att',
       'Raw_airEPA_per_Drive', 'epa_PACR', 'airEPA_per_Att', 'airEPA_per_Comp',
       'airEPA_per_Drive', 'wpa_PACR', 'Raw_airWPA_per_Att',
       'Raw_airWPA_per_Drive', 'airWPA_per_Att', 'airWPA_per_Comp',
       'airWPA_per_Drive', 'yacEPA_per_Att', 'yacEPA_per_Comp',
       'yacEPA_Rec_per_Drive', 'yacEPA_Drop_per_Drive', 'passer_gsis'],
      dtype='object')

In [15]:
print(season_passing_df.columns)

Index(['Season', 'passer_player_id', 'Player_Name', 'Attempts', 'Completions',
       'Drives', 'Total_Yards', 'Total_Yards_8', 'Total_Yards_4',
       'Total_Raw_AirYards', 'Total_Comp_AirYards', 'TimesHit',
       'Interceptions', 'Interceptions_8', 'Interceptions_4', 'TDs', 'TDs_8',
       'TDs_4', 'Air_TDs', 'Total_EPA', 'Success_Rate', 'EPA_Per_Comp',
       'EPA_Comp_Perc', 'Total_WPA', 'Win_Success_Rate', 'WPA_per_Comp',
       'WPA_Comp_Perc', 'Total_Clutch_EPA', 'airEPA_Comp', 'airEPA_Incomp',
       'Total_Raw_airEPA', 'air_Success_Rate', 'air_Comp_Success_Rate',
       'airWPA_Comp', 'airWPA_Incomp', 'Total_Raw_airWPA',
       'air_Win_Success_Rate', 'air_Comp_Win_Success_Rate', 'yacEPA_Comp',
       'yacEPA_Drop', 'Total_yacEPA', 'yacWPA_Comp', 'yacWPA_Drop',
       'Total_yacWPA', 'yac_Success_Rate', 'yac_Rec_Success_Rate',
       'yac_Win_Success_Rate', 'yac_Complete_Win_Success_Rate', 'Comp_Perc',
       'Yards_Per_Att', 'Yards_Per_Comp', 'Yards_Per_Drive',
       'Raw_AirYards_per_Att', 'Comp_AirYards_per_Att',
       'Raw_AirYards_per_Comp', 'Comp_AirYards_per_Comp',
       'Raw_AirYards_per_Drive', 'Comp_AirYards_per_Drive', 'PACR',
       'TimesHit_per_Drive', 'aPACR', 'Air_TD_Rate', 'TD_to_Int',
       'EPA_per_Att', 'TD_per_Att', 'Air_TD_per_Att', 'Int_per_Att',
       'TD_per_Comp', 'Air_TD_per_Comp', 'TD_per_Drive', 'Air_TD_per_Drive',
       'Int_per_Drive', 'EPA_per_Drive', 'WPA_per_Att', 'WPA_per_Drive',
       'Clutch_EPA_per_Att', 'Clutch_EPA_per_Drive', 'Raw_airEPA_per_Att',
       'Raw_airEPA_per_Drive', 'epa_PACR', 'airEPA_per_Att', 'airEPA_per_Comp',
       'airEPA_per_Drive', 'wpa_PACR', 'Raw_airWPA_per_Att',
       'Raw_airWPA_per_Drive', 'airWPA_per_Att', 'airWPA_per_Comp',
       'airWPA_per_Drive', 'yacEPA_per_Att', 'yacEPA_per_Comp',
       'yacEPA_Rec_per_Drive', 'yacEPA_Drop_per_Drive', 'passer_gsis'],
      dtype='object')

In [16]:
season_rushing_df.columns

Index(['Season', 'rusher_player_id', 'Player_Name', 'Carries', 'Drives',
       'Total_Yards', 'Total_Yards_8', 'Total_Yards_4', 'Fumbles', 'TDs',
       'TDs_8', 'TDs_4', 'Total_EPA', 'Success_Rate', 'EPA_Ratio', 'Total_WPA',
       'Win_Success_Rate', 'WPA_Ratio', 'Total_Clutch_EPA', 'Car_per_Drive',
       'Yards_per_Car', 'Yards_per_Drive', 'TD_to_Fumbles', 'EPA_per_Car',
       'TD_per_Car', 'Fumbles_per_Car', 'Fumbles_per_Drive', 'TD_Drive',
       'EPA_per_Drive', 'WPA_per_Drive', 'WPA_per_Car', 'Clutch_EPA_per_Car',
       'Clutch_EPA_per_Drive'],
      dtype='object')

In [17]:
season_receiving_df.columns

Index(['Season', 'receiver_player_id', 'Player_Name', 'Targets', 'Receptions',
       'Receptions_8', 'Receptions_4', 'Drives', 'Total_Yards',
       'Total_Yards_8', 'Total_Yards_4', 'Total_Raw_YAC', 'Total_Caught_YAC',
       'Total_Dropped_YAC', 'Fumbles', 'TDs', 'TDs_8', 'TDs_4', 'AC_TDs',
       'Total_EPA', 'Success_Rate', 'EPA_per_Rec', 'EPA_Rec_Perc', 'Total_WPA',
       'Win_Success_Rate', 'WPA_per_Rec', 'WPA_Rec_Perc', 'Total_Clutch_EPA',
       'Total_Raw_AirYards', 'Total_Caught_AirYards', 'Total_Raw_airEPA',
       'Total_Caught_airEPA', 'Total_Raw_airWPA', 'Total_Caught_airWPA',
       'yacEPA_Rec', 'yacEPA_Drop', 'Total_yacEPA', 'yacWPA_Rec',
       'yacWPA_Drop', 'Total_yacWPA', 'yac_Success_Rate',
       'yac_Rec_Success_Rate', 'air_Success_Rate', 'air_Rec_Success_Rate',
       'yac_Win_Success_Rate', 'yac_Rec_Win_Success_Rate',
       'air_Win_Success_Rate', 'air_Rec_Win_Success_Rate', 'Targets_per_Drive',
       'Rec_per_Drive', 'Yards_per_Drive', 'Yards_per_Rec', 'Yards_per_Target',
       'YAC_per_Target', 'Caught_YAC_per_Target', 'Dropped_YAC_per_Target',
       'YAC_per_Rec', 'Caught_YAC_per_Rec', 'Dropped_YAC_per_Rec',
       'YAC_per_Drive', 'Caught_YAC_per_Drive', 'Dropped_YAC_per_Drive',
       'Rec_Percentage', 'TDs_per_Drive', 'Fumbles_per_Drive',
       'AC_TDs_per_Drive', 'AC_TD_Rate', 'TD_to_Fumbles', 'EPA_per_Drives',
       'EPA_per_Target', 'TD_per_Targets', 'Fumbles_per_Receptions',
       'TD_per_Rec', 'WPA_per_Drive', 'WPA_per_Target', 'Clutch_EPA_per_Drive',
       'PACR', 'Raw_AirYards_per_Target', 'RACR', 'Raw_airEPA_per_Drive',
       'Caught_airEPA_per_Drive', 'airEPA_per_Target',
       'Caught_airEPA_per_Target', 'epa_RACR', 'Raw_airWPA_per_Drive',
       'Caught_airWPA_per_Drive', 'airWPA_per_Target',
       'Caught_airWPA_per_Target', 'yacEPA_per_Target', 'yacEPA_per_Rec',
       'yacEPA_Rec_per_Drive', 'yacEPA_Drop_per_Drive', 'yacWPA_per_Target',
       'yacWPA_per_Rec', 'yacWPA_Rec_per_Drive', 'yacWPA_Drop_per_Drive',
       'wpa_RACR', 'receiver_gsis'],
      dtype='object')

In [18]:
all_data_df = season_rushing_df.merge(season_receiving_df, left_on=['rusher_player_id', 'Season'], right_on=['receiver_player_id', 'Season'], how='outer')

In [19]:
all_data_df.columns

Index(['Season', 'rusher_player_id', 'Player_Name_x', 'Carries', 'Drives_x',
       'Total_Yards_x', 'Total_Yards_8_x', 'Total_Yards_4_x', 'Fumbles_x',
       'TDs_x',
       ...
       'yacEPA_per_Target', 'yacEPA_per_Rec', 'yacEPA_Rec_per_Drive',
       'yacEPA_Drop_per_Drive', 'yacWPA_per_Target', 'yacWPA_per_Rec',
       'yacWPA_Rec_per_Drive', 'yacWPA_Drop_per_Drive', 'wpa_RACR',
       'receiver_gsis'],
      dtype='object', length=130)

In [20]:
all_data_df.columns.toList()

AttributeError: 'Index' object has no attribute 'toList'

In [21]:
empty_columns = all_data_df.columns[all_data_df.isna().all()].tolist()
print("all empty columns after the first merge")
print(empty_columns)

all empty columns after the first merge
[]

In [22]:
all_data_df = all_data_df.merge(season_passing_df, left_on=['rusher_player_id', 'Season'], right_on=['passer_player_id', 'Season'], how='outer')

In [23]:
all_data_df.columns

Index(['Season', 'rusher_player_id', 'Player_Name_x', 'Carries', 'Drives_x',
       'Total_Yards_x', 'Total_Yards_8_x', 'Total_Yards_4_x', 'Fumbles_x',
       'TDs_x',
       ...
       'Raw_airWPA_per_Att', 'Raw_airWPA_per_Drive_y', 'airWPA_per_Att',
       'airWPA_per_Comp', 'airWPA_per_Drive', 'yacEPA_per_Att',
       'yacEPA_per_Comp', 'yacEPA_Rec_per_Drive_y', 'yacEPA_Drop_per_Drive_y',
       'passer_gsis'],
      dtype='object', length=223)

In [24]:
print(all_data_df.columns)

Index(['Season', 'rusher_player_id', 'Player_Name_x', 'Carries', 'Drives_x',
       'Total_Yards_x', 'Total_Yards_8_x', 'Total_Yards_4_x', 'Fumbles_x',
       'TDs_x',
       ...
       'Raw_airWPA_per_Att', 'Raw_airWPA_per_Drive_y', 'airWPA_per_Att',
       'airWPA_per_Comp', 'airWPA_per_Drive', 'yacEPA_per_Att',
       'yacEPA_per_Comp', 'yacEPA_Rec_per_Drive_y', 'yacEPA_Drop_per_Drive_y',
       'passer_gsis'],
      dtype='object', length=223)

In [25]:
print(list(all_data_df.columns))

['Season', 'rusher_player_id', 'Player_Name_x', 'Carries', 'Drives_x', 'Total_Yards_x', 'Total_Yards_8_x', 'Total_Yards_4_x', 'Fumbles_x', 'TDs_x', 'TDs_8_x', 'TDs_4_x', 'Total_EPA_x', 'Success_Rate_x', 'EPA_Ratio', 'Total_WPA_x', 'Win_Success_Rate_x', 'WPA_Ratio', 'Total_Clutch_EPA_x', 'Car_per_Drive', 'Yards_per_Car', 'Yards_per_Drive_x', 'TD_to_Fumbles_x', 'EPA_per_Car', 'TD_per_Car', 'Fumbles_per_Car', 'Fumbles_per_Drive_x', 'TD_Drive', 'EPA_per_Drive_x', 'WPA_per_Drive_x', 'WPA_per_Car', 'Clutch_EPA_per_Car', 'Clutch_EPA_per_Drive_x', 'receiver_player_id', 'Player_Name_y', 'Targets', 'Receptions', 'Receptions_8', 'Receptions_4', 'Drives_y', 'Total_Yards_y', 'Total_Yards_8_y', 'Total_Yards_4_y', 'Total_Raw_YAC', 'Total_Caught_YAC', 'Total_Dropped_YAC', 'Fumbles_y', 'TDs_y', 'TDs_8_y', 'TDs_4_y', 'AC_TDs', 'Total_EPA_y', 'Success_Rate_y', 'EPA_per_Rec', 'EPA_Rec_Perc', 'Total_WPA_y', 'Win_Success_Rate_y', 'WPA_per_Rec', 'WPA_Rec_Perc', 'Total_Clutch_EPA_y', 'Total_Raw_AirYards_x', 'Total_Caught_AirYards', 'Total_Raw_airEPA_x', 'Total_Caught_airEPA', 'Total_Raw_airWPA_x', 'Total_Caught_airWPA', 'yacEPA_Rec', 'yacEPA_Drop_x', 'Total_yacEPA_x', 'yacWPA_Rec', 'yacWPA_Drop_x', 'Total_yacWPA_x', 'yac_Success_Rate_x', 'yac_Rec_Success_Rate_x', 'air_Success_Rate_x', 'air_Rec_Success_Rate', 'yac_Win_Success_Rate_x', 'yac_Rec_Win_Success_Rate', 'air_Win_Success_Rate_x', 'air_Rec_Win_Success_Rate', 'Targets_per_Drive', 'Rec_per_Drive', 'Yards_per_Drive_y', 'Yards_per_Rec', 'Yards_per_Target', 'YAC_per_Target', 'Caught_YAC_per_Target', 'Dropped_YAC_per_Target', 'YAC_per_Rec', 'Caught_YAC_per_Rec', 'Dropped_YAC_per_Rec', 'YAC_per_Drive', 'Caught_YAC_per_Drive', 'Dropped_YAC_per_Drive', 'Rec_Percentage', 'TDs_per_Drive', 'Fumbles_per_Drive_y', 'AC_TDs_per_Drive', 'AC_TD_Rate', 'TD_to_Fumbles_y', 'EPA_per_Drives', 'EPA_per_Target', 'TD_per_Targets', 'Fumbles_per_Receptions', 'TD_per_Rec', 'WPA_per_Drive_y', 'WPA_per_Target', 'Clutch_EPA_per_Drive_y', 'PACR_x', 'Raw_AirYards_per_Target', 'RACR', 'Raw_airEPA_per_Drive_x', 'Caught_airEPA_per_Drive', 'airEPA_per_Target', 'Caught_airEPA_per_Target', 'epa_RACR', 'Raw_airWPA_per_Drive_x', 'Caught_airWPA_per_Drive', 'airWPA_per_Target', 'Caught_airWPA_per_Target', 'yacEPA_per_Target', 'yacEPA_per_Rec', 'yacEPA_Rec_per_Drive_x', 'yacEPA_Drop_per_Drive_x', 'yacWPA_per_Target', 'yacWPA_per_Rec', 'yacWPA_Rec_per_Drive', 'yacWPA_Drop_per_Drive', 'wpa_RACR', 'receiver_gsis', 'passer_player_id', 'Player_Name', 'Attempts', 'Completions', 'Drives', 'Total_Yards', 'Total_Yards_8', 'Total_Yards_4', 'Total_Raw_AirYards_y', 'Total_Comp_AirYards', 'TimesHit', 'Interceptions', 'Interceptions_8', 'Interceptions_4', 'TDs', 'TDs_8', 'TDs_4', 'Air_TDs', 'Total_EPA', 'Success_Rate', 'EPA_Per_Comp', 'EPA_Comp_Perc', 'Total_WPA', 'Win_Success_Rate', 'WPA_per_Comp', 'WPA_Comp_Perc', 'Total_Clutch_EPA', 'airEPA_Comp', 'airEPA_Incomp', 'Total_Raw_airEPA_y', 'air_Success_Rate_y', 'air_Comp_Success_Rate', 'airWPA_Comp', 'airWPA_Incomp', 'Total_Raw_airWPA_y', 'air_Win_Success_Rate_y', 'air_Comp_Win_Success_Rate', 'yacEPA_Comp', 'yacEPA_Drop_y', 'Total_yacEPA_y', 'yacWPA_Comp', 'yacWPA_Drop_y', 'Total_yacWPA_y', 'yac_Success_Rate_y', 'yac_Rec_Success_Rate_y', 'yac_Win_Success_Rate_y', 'yac_Complete_Win_Success_Rate', 'Comp_Perc', 'Yards_Per_Att', 'Yards_Per_Comp', 'Yards_Per_Drive', 'Raw_AirYards_per_Att', 'Comp_AirYards_per_Att', 'Raw_AirYards_per_Comp', 'Comp_AirYards_per_Comp', 'Raw_AirYards_per_Drive', 'Comp_AirYards_per_Drive', 'PACR_y', 'TimesHit_per_Drive', 'aPACR', 'Air_TD_Rate', 'TD_to_Int', 'EPA_per_Att', 'TD_per_Att', 'Air_TD_per_Att', 'Int_per_Att', 'TD_per_Comp', 'Air_TD_per_Comp', 'TD_per_Drive', 'Air_TD_per_Drive', 'Int_per_Drive', 'EPA_per_Drive_y', 'WPA_per_Att', 'WPA_per_Drive', 'Clutch_EPA_per_Att', 'Clutch_EPA_per_Drive', 'Raw_airEPA_per_Att', 'Raw_airEPA_per_Drive_y', 'epa_PACR', 'airEPA_per_Att', 'airEPA_per_Comp', 'airEPA_per_Drive', 'wpa_PACR', 'Raw_airWPA_per_Att', 'Raw_airWPA_per_Drive_y', 'airWPA_per_Att', 'airWPA_per_Comp', 'airWPA_per_Drive', 'yacEPA_per_Att', 'yacEPA_per_Comp', 'yacEPA_Rec_per_Drive_y', 'yacEPA_Drop_per_Drive_y', 'passer_gsis']

In [26]:
empty_columns = all_data_df.columns[all_data_df.isna().all()].tolist()
print("all empty columns after the second merge")
print(empty_columns)

all empty columns after the second merge
[]

In [27]:
all_data_df['gsis_id'] = all_data_df['rusher_player_id'].combine_first(all_data_df['receiver_gsis']).combine_first(all_data_df['passer_gsis'])

In [28]:
all_data_df[["gsis_id"]].head(50)

       gsis_id
0   00-0019641
1   00-0025394
2   00-0026164
3   00-0022736
4   00-0023439
5   00-0024275
6   00-0022984
7   00-0026195
8   00-0024245
9   00-0026184
10  00-0026988
11  00-0017915
12  00-0026163
13  00-0024204
14  00-0020536
15  00-0023500
16  00-0023544
17  00-0023545
18  00-0026153
19  00-0024242
20  00-0026204
21  00-0023440
22  00-0024236
23  00-0027007
24  00-0024359
25  00-0026213
26  00-0024813
27  00-0024011
28  00-0021976
29  00-0022821
30  00-0022840
31  00-0025637
32  00-0026899
33  00-0027029
34  00-0026289
35  00-0023437
36  00-0026162
37  00-0019693
38  00-0025631
39  00-0022178
40  00-0026229
41  00-0022093
42  00-0021179
43  00-0025487
44  00-0020270
45  00-0025399
46  00-0022770
47  00-0026373
48  00-0026144
49  00-0021314

In [29]:
all_data_df['gsis_id'].isna().sum()

0

In [30]:
all_data_df[["Player_Name","Player_Name_x","Player_Name_y"]].head(50)

    Player_Name Player_Name_x Player_Name_y
0           NaN       T.Jones       T.Jones
1           NaN    A.Peterson    A.Peterson
2     C.Johnson     C.Johnson     C.Johnson
3           NaN     S.Jackson     S.Jackson
4           NaN      C.Benson      C.Benson
5           NaN  M.Jones-Drew  M.Jones-Drew
6           NaN       R.Grant       R.Grant
7        R.Rice        R.Rice        R.Rice
8       J.Addai       J.Addai       J.Addai
9           NaN       M.Forte       M.Forte
10          NaN      K.Moreno      K.Moreno
11   R.Williams    R.Williams    R.Williams
12          NaN  R.Mendenhall  R.Mendenhall
13    F.Jackson     F.Jackson     F.Jackson
14  L.Tomlinson   L.Tomlinson   L.Tomlinson
15          NaN        F.Gore        F.Gore
16          NaN      M.Barber      M.Barber
17          NaN      B.Jacobs      B.Jacobs
18          NaN     J.Stewart     J.Stewart
19          NaN    D.Williams    D.Williams
20          NaN       K.Smith       K.Smith
21          NaN    C.Williams    C.Williams
22          NaN     L.Maroney     L.Maroney
23          NaN       C.Wells       C.Wells
24          NaN    J.Harrison    J.Harrison
25          NaN     J.Charles     J.Charles
26          NaN      P.Thomas      P.Thomas
27          NaN        M.Bell        M.Bell
28          NaN     L.Johnson     L.Johnson
29          NaN      M.Turner      M.Turner
30          NaN       J.Jones       J.Jones
31          NaN    A.Bradshaw    A.Bradshaw
32          NaN      S.Greene      S.Greene
33          NaN       L.McCoy       L.McCoy
34          NaN   T.Hightower   T.Hightower
35      R.Brown       R.Brown       R.Brown
36          NaN       F.Jones       F.Jones
37          NaN       J.Lewis       J.Lewis
38          NaN    J.Snelling    J.Snelling
39          NaN     W.McGahee     W.McGahee
40          NaN      S.Slaton      S.Slaton
41          NaN      J.Fargas      J.Fargas
42     C.Portis      C.Portis      C.Portis
43       M.Bush        M.Bush        M.Bush
44          NaN  C.Buckhalter  C.Buckhalter
45          NaN       M.Lynch       M.Lynch
46          NaN        D.Ward        D.Ward
47          NaN     J.Forsett     J.Forsett
48          NaN    D.McFadden    D.McFadden
49          NaN      C.Taylor      C.Taylor

In [31]:
all_data_df['Name'] = all_data_df['Player_Name'].combine_first(all_data_df['Player_Name_x']).combine_first(all_data_df['Player_Name_y'])

In [32]:
empty_columns = all_data_df.columns[all_data_df.isna().all()].tolist()
print("all empty columns after the creating the gsis_id and Name columns")
print(empty_columns)

all empty columns after the creating the gsis_id and Name columns
[]

In [33]:
print(list(all_data_df.columns))

['Season', 'rusher_player_id', 'Player_Name_x', 'Carries', 'Drives_x', 'Total_Yards_x', 'Total_Yards_8_x', 'Total_Yards_4_x', 'Fumbles_x', 'TDs_x', 'TDs_8_x', 'TDs_4_x', 'Total_EPA_x', 'Success_Rate_x', 'EPA_Ratio', 'Total_WPA_x', 'Win_Success_Rate_x', 'WPA_Ratio', 'Total_Clutch_EPA_x', 'Car_per_Drive', 'Yards_per_Car', 'Yards_per_Drive_x', 'TD_to_Fumbles_x', 'EPA_per_Car', 'TD_per_Car', 'Fumbles_per_Car', 'Fumbles_per_Drive_x', 'TD_Drive', 'EPA_per_Drive_x', 'WPA_per_Drive_x', 'WPA_per_Car', 'Clutch_EPA_per_Car', 'Clutch_EPA_per_Drive_x', 'receiver_player_id', 'Player_Name_y', 'Targets', 'Receptions', 'Receptions_8', 'Receptions_4', 'Drives_y', 'Total_Yards_y', 'Total_Yards_8_y', 'Total_Yards_4_y', 'Total_Raw_YAC', 'Total_Caught_YAC', 'Total_Dropped_YAC', 'Fumbles_y', 'TDs_y', 'TDs_8_y', 'TDs_4_y', 'AC_TDs', 'Total_EPA_y', 'Success_Rate_y', 'EPA_per_Rec', 'EPA_Rec_Perc', 'Total_WPA_y', 'Win_Success_Rate_y', 'WPA_per_Rec', 'WPA_Rec_Perc', 'Total_Clutch_EPA_y', 'Total_Raw_AirYards_x', 'Total_Caught_AirYards', 'Total_Raw_airEPA_x', 'Total_Caught_airEPA', 'Total_Raw_airWPA_x', 'Total_Caught_airWPA', 'yacEPA_Rec', 'yacEPA_Drop_x', 'Total_yacEPA_x', 'yacWPA_Rec', 'yacWPA_Drop_x', 'Total_yacWPA_x', 'yac_Success_Rate_x', 'yac_Rec_Success_Rate_x', 'air_Success_Rate_x', 'air_Rec_Success_Rate', 'yac_Win_Success_Rate_x', 'yac_Rec_Win_Success_Rate', 'air_Win_Success_Rate_x', 'air_Rec_Win_Success_Rate', 'Targets_per_Drive', 'Rec_per_Drive', 'Yards_per_Drive_y', 'Yards_per_Rec', 'Yards_per_Target', 'YAC_per_Target', 'Caught_YAC_per_Target', 'Dropped_YAC_per_Target', 'YAC_per_Rec', 'Caught_YAC_per_Rec', 'Dropped_YAC_per_Rec', 'YAC_per_Drive', 'Caught_YAC_per_Drive', 'Dropped_YAC_per_Drive', 'Rec_Percentage', 'TDs_per_Drive', 'Fumbles_per_Drive_y', 'AC_TDs_per_Drive', 'AC_TD_Rate', 'TD_to_Fumbles_y', 'EPA_per_Drives', 'EPA_per_Target', 'TD_per_Targets', 'Fumbles_per_Receptions', 'TD_per_Rec', 'WPA_per_Drive_y', 'WPA_per_Target', 'Clutch_EPA_per_Drive_y', 'PACR_x', 'Raw_AirYards_per_Target', 'RACR', 'Raw_airEPA_per_Drive_x', 'Caught_airEPA_per_Drive', 'airEPA_per_Target', 'Caught_airEPA_per_Target', 'epa_RACR', 'Raw_airWPA_per_Drive_x', 'Caught_airWPA_per_Drive', 'airWPA_per_Target', 'Caught_airWPA_per_Target', 'yacEPA_per_Target', 'yacEPA_per_Rec', 'yacEPA_Rec_per_Drive_x', 'yacEPA_Drop_per_Drive_x', 'yacWPA_per_Target', 'yacWPA_per_Rec', 'yacWPA_Rec_per_Drive', 'yacWPA_Drop_per_Drive', 'wpa_RACR', 'receiver_gsis', 'passer_player_id', 'Player_Name', 'Attempts', 'Completions', 'Drives', 'Total_Yards', 'Total_Yards_8', 'Total_Yards_4', 'Total_Raw_AirYards_y', 'Total_Comp_AirYards', 'TimesHit', 'Interceptions', 'Interceptions_8', 'Interceptions_4', 'TDs', 'TDs_8', 'TDs_4', 'Air_TDs', 'Total_EPA', 'Success_Rate', 'EPA_Per_Comp', 'EPA_Comp_Perc', 'Total_WPA', 'Win_Success_Rate', 'WPA_per_Comp', 'WPA_Comp_Perc', 'Total_Clutch_EPA', 'airEPA_Comp', 'airEPA_Incomp', 'Total_Raw_airEPA_y', 'air_Success_Rate_y', 'air_Comp_Success_Rate', 'airWPA_Comp', 'airWPA_Incomp', 'Total_Raw_airWPA_y', 'air_Win_Success_Rate_y', 'air_Comp_Win_Success_Rate', 'yacEPA_Comp', 'yacEPA_Drop_y', 'Total_yacEPA_y', 'yacWPA_Comp', 'yacWPA_Drop_y', 'Total_yacWPA_y', 'yac_Success_Rate_y', 'yac_Rec_Success_Rate_y', 'yac_Win_Success_Rate_y', 'yac_Complete_Win_Success_Rate', 'Comp_Perc', 'Yards_Per_Att', 'Yards_Per_Comp', 'Yards_Per_Drive', 'Raw_AirYards_per_Att', 'Comp_AirYards_per_Att', 'Raw_AirYards_per_Comp', 'Comp_AirYards_per_Comp', 'Raw_AirYards_per_Drive', 'Comp_AirYards_per_Drive', 'PACR_y', 'TimesHit_per_Drive', 'aPACR', 'Air_TD_Rate', 'TD_to_Int', 'EPA_per_Att', 'TD_per_Att', 'Air_TD_per_Att', 'Int_per_Att', 'TD_per_Comp', 'Air_TD_per_Comp', 'TD_per_Drive', 'Air_TD_per_Drive', 'Int_per_Drive', 'EPA_per_Drive_y', 'WPA_per_Att', 'WPA_per_Drive', 'Clutch_EPA_per_Att', 'Clutch_EPA_per_Drive', 'Raw_airEPA_per_Att', 'Raw_airEPA_per_Drive_y', 'epa_PACR', 'airEPA_per_Att', 'airEPA_per_Comp', 'airEPA_per_Drive', 'wpa_PACR', 'Raw_airWPA_per_Att', 'Raw_airWPA_per_Drive_y', 'airWPA_per_Att', 'airWPA_per_Comp', 'airWPA_per_Drive', 'yacEPA_per_Att', 'yacEPA_per_Comp', 'yacEPA_Rec_per_Drive_y', 'yacEPA_Drop_per_Drive_y', 'passer_gsis', 'gsis_id', 'Name']

In [36]:
all_data_df[["Name","gsis_id"]].head(10)

           Name     gsis_id
0       T.Jones  00-0019641
1    A.Peterson  00-0025394
2     C.Johnson  00-0026164
3     S.Jackson  00-0022736
4      C.Benson  00-0023439
5  M.Jones-Drew  00-0024275
6       R.Grant  00-0022984
7        R.Rice  00-0026195
8       J.Addai  00-0024245
9       M.Forte  00-0026184

In [37]:
all_data_df.replace([np.inf, -np.inf], np.nan, inplace=True)

# 2. Replace NA values in numeric columns with 0
numerics = all_data_df.select_dtypes(include=[np.number]).columns
all_data_df[numerics] = all_data_df[numerics].fillna(0)

# 3. Create new columns for fantasy points calculations
fantasy_points = (all_data_df['Total_Yards_x'] * rush_yards +
                                all_data_df['TDs_x'] * rush_td +
                                (all_data_df['Fumbles_x'] + all_data_df['Fumbles_y']) * fmb +
                                all_data_df['Total_Yards_y'] * receiving_yards +
                                all_data_df['TDs_y'] * receiving_td +
                                all_data_df['Receptions'] * ppr +
                                all_data_df['Total_Yards'] * pass_yards +
                                all_data_df['TDs'] * pass_td +
                                all_data_df['Interceptions'] * interception)

fantasy_points_8 = (all_data_df['Total_Yards_8_x'] * rush_yards +
                                   all_data_df['TDs_8_x'] * rush_td +
                                   all_data_df['Total_Yards_8_y'] * receiving_yards +
                                   all_data_df['TDs_8_y'] * receiving_td +
                                   all_data_df['Receptions_8'] * ppr +
                                   all_data_df['Total_Yards_8'] * pass_yards +
                                   all_data_df['TDs_8'] * pass_td
                                   )

fantasy_points_4 = (all_data_df['Total_Yards_4_x'] * rush_yards +
                                   all_data_df['TDs_4_x'] * rush_td +
                                   all_data_df['Total_Yards_4_y'] * receiving_yards +
                                   all_data_df['TDs_4_y'] * receiving_td +
                                   all_data_df['Receptions_4'] * ppr +
                                   all_data_df['Total_Yards_4'] * pass_yards +
                                   all_data_df['TDs_4'] * pass_td
                                   )

In [38]:
all_data_df["fantasyPoints"] = fantasy_points

/var/folders/8q/mwds2yxx4538sqk5yqqrm4nr0000gn/T/ipykernel_52274/811551684.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_data_df["fantasyPoints"] = fantasy_points

In [39]:
all_data_df["fantasy_points_8"] = fantasy_points_8
all_data_df["fantasy_points_4"] = fantasy_points_4

/var/folders/8q/mwds2yxx4538sqk5yqqrm4nr0000gn/T/ipykernel_52274/1957681361.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_data_df["fantasy_points_8"] = fantasy_points_8
/var/folders/8q/mwds2yxx4538sqk5yqqrm4nr0000gn/T/ipykernel_52274/1957681361.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_data_df["fantasy_points_4"] = fantasy_points_4

In [44]:
all_data_df[["Name","fantasyPoints","fantasy_points_8","fantasy_points_4","Season"]].head(25)

            Name  fantasyPoints  fantasy_points_8  fantasy_points_4  Season
0        T.Jones         258.50            139.20              86.7    2009
1     A.Peterson         364.30            205.40             132.5    2009
2      C.Johnson         391.10            221.80             114.8    2009
3      S.Jackson         239.80            120.80              29.9    2009
4       C.Benson         214.30             80.00              63.3    2009
5   M.Jones-Drew         321.50            136.00              69.9    2009
6        R.Grant         244.30            131.80              81.2    2009
7         R.Rice         371.70            196.80             126.3    2009
8        J.Addai         289.78            152.10              80.4    2009
9        M.Forte         209.20            103.20              42.8    2009
10      K.Moreno         196.00            120.30              59.0    2009
11    R.Williams         239.70            129.30              55.2    2009
12  R.Mendenhall         203.90            111.80              55.1    2009
13     F.Jackson         220.08            136.18              74.4    2009
14   L.Tomlinson         181.80            125.90              58.1    2009
15        F.Gore         276.60            160.90              93.7    2009
16      M.Barber         181.10             99.70              61.8    2009
17      B.Jacobs         157.90             80.40              26.4    2009
18     J.Stewart         205.20            125.50              77.9    2009
19    D.Williams         208.10             50.80              14.3    2009
20       K.Smith         179.60             76.50              10.8    2009
21    C.Williams         178.50             91.70              52.5    2009
22     L.Maroney         145.80             91.50              29.6    2009
23       C.Wells         161.40            120.70              70.6    2009
24    J.Harrison         186.20            129.70              97.2    2009

In [45]:
all_data_df = all_data_df.copy()

In [46]:
all_data_df[["Name","fantasyPoints","fantasy_points_8","fantasy_points_4","Season"]].head(25)

            Name  fantasyPoints  fantasy_points_8  fantasy_points_4  Season
0        T.Jones         258.50            139.20              86.7    2009
1     A.Peterson         364.30            205.40             132.5    2009
2      C.Johnson         391.10            221.80             114.8    2009
3      S.Jackson         239.80            120.80              29.9    2009
4       C.Benson         214.30             80.00              63.3    2009
5   M.Jones-Drew         321.50            136.00              69.9    2009
6        R.Grant         244.30            131.80              81.2    2009
7         R.Rice         371.70            196.80             126.3    2009
8        J.Addai         289.78            152.10              80.4    2009
9        M.Forte         209.20            103.20              42.8    2009
10      K.Moreno         196.00            120.30              59.0    2009
11    R.Williams         239.70            129.30              55.2    2009
12  R.Mendenhall         203.90            111.80              55.1    2009
13     F.Jackson         220.08            136.18              74.4    2009
14   L.Tomlinson         181.80            125.90              58.1    2009
15        F.Gore         276.60            160.90              93.7    2009
16      M.Barber         181.10             99.70              61.8    2009
17      B.Jacobs         157.90             80.40              26.4    2009
18     J.Stewart         205.20            125.50              77.9    2009
19    D.Williams         208.10             50.80              14.3    2009
20       K.Smith         179.60             76.50              10.8    2009
21    C.Williams         178.50             91.70              52.5    2009
22     L.Maroney         145.80             91.50              29.6    2009
23       C.Wells         161.40            120.70              70.6    2009
24    J.Harrison         186.20            129.70              97.2    2009

In [47]:
len(all_data_df)

8420

In [48]:
len(all_rosters)

34980

In [49]:
all_rosters = all_rosters.drop_duplicates()

In [50]:
len(all_rosters)

34980

In [51]:
all_rosters.rename(columns={'full_name': 'full_player_name'}, inplace=True)

In [52]:
list(all_rosters)

['gsis_id', 'season', 'team', 'full_player_name', 'position']

In [53]:
all_rosters.head(25)

   gsis_id  season team             full_player_name position
0      NaN    2009  ARZ                  Ben Claxton        C
1      NaN    2009  ARZ                Lyle Sendlein        C
2      NaN    2009  ARZ                Michael Adams       CB
3      NaN    2009  ARZ                  Ralph Brown       CB
4      NaN    2009  ARZ              Bryant McFadden       CB
5      NaN    2009  ARZ  Dominique Rodgers-Cromartie       CB
6      NaN    2009  ARZ                Gregory Toler       CB
7      NaN    2009  ARZ              Calais Campbell       DE
8      NaN    2009  ARZ                Kenny Iwebema       DE
9      NaN    2009  ARZ                  Alan Branch       DT
10     NaN    2009  ARZ                 Jeremy Clark       DT
11     NaN    2009  ARZ              Darnell Dockett       DT
12     NaN    2009  ARZ           Nehemiah Broughton       FB
13     NaN    2009  ARZ                  Dan Kreider       FB
14     NaN    2009  ARZ               Rashad Johnson       FS
15     NaN    2009  ARZ                 Antrel Rolle       FS
16     NaN    2009  ARZ               Jeremy Bridges        G
17     NaN    2009  ARZ                Brandon Keith        G
18     NaN    2009  ARZ                  Deuce Lutui        G
19     NaN    2009  ARZ                 Reggie Wells        G
20     NaN    2009  ARZ                 Monty Beisel      ILB
21     NaN    2009  ARZ                Karlos Dansby      ILB
22     NaN    2009  ARZ                 Gerald Hayes      ILB
23     NaN    2009  ARZ                Reggie Walker      ILB
24     NaN    2009  ARZ                 Neil Rackers        K